### ISSUE TITLE
quant_lenet file has error

### ISSUE THREAD

**Issue by mustafatasci42** [vishnukashyap/MNIST-QNN#2]
![error](https://user-images.githubusercontent.com/15524481/183890242-e6cbaf66-b7f3-489c-8285-143e1336868a.png)
Thanks for this useful repo.
qnn_lenet.py file has error in lenet class fc1 layer. 

layer size should be 16x4x4 not 16x5x5

**Comment by vishnukashyap** [comment]
Hi, thanks for pointing it out.
I have added the fix, 16x5x5 is the input size of FC1 for CIFAR10, while for MNIST it is 16x4x4, fixed it so that the values are taken as per the selected dataset.
